### ISSUE TITLE
Keys to actions are hardcoded

### ISSUE THREAD

**Issue by VladisCrafter** [kiber-pacan/item-placer-arch#1]
Please consider making keybindings for placing an item and rotating it configurable and not hardcoded as `V` and `alt` respectively. That would be a lot more convinient for modpacks with those keys being already in use. Thanks!

###### P.S. and maybe also an option to mute the sound of placing the item and picking it up.

**Comment by kiber-pacan** [comment]
ok

**Comment by kiber-pacan** [comment]
thx

**Comment by kiber-pacan** [comment]
done (only keys)
