### ISSUE TITLE
[Feature Request] Select only directed hovered item

### ISSUE THREAD

**Issue by Disketaa** [kiber-pacan/item-placer-arch#14]
![image](https://github.com/user-attachments/assets/aaac473b-6d4f-474d-b4c7-c0294d8cb62b)
For now if you hovers on 2+ items placed together, you'll break both of them. 
It's uncomfortable to break only one item, cause of item frame works with direction hovering

**Comment by kiber-pacan** [comment]
there is right click for that purpose
