### ISSUE TITLE
[Feature Request] Ability to disable air-V-placement, similar to Item frames

### ISSUE THREAD

**Issue by Disketaa** [kiber-pacan/item-placer-arch#15]
![image](https://github.com/user-attachments/assets/bb7ffd9e-e2f0-458c-aa86-db95582332c4)

**Comment by kiber-pacan** [comment]
didn't understand your request

**Comment by Disketaa** [comment]
Currently items can be V-placed (placed in world via V-key) on top of each other. Then if you will destroy a block underneath them, they won't fall, like item-frames.

I'm wandering about something similar to item frame mechanic, when they need support block to keep placed

**Comment by kiber-pacan** [comment]
I don't want to limit decoration possibilites
